query ClosestRelationship(
  $treeId: UUID!
  $fromId: UUID!
  $toId: UUID!
  $maleOnly: Boolean = false
) {
  closestRelationship(
    treeId: $treeId
    fromPersonId: $fromId
    toPersonId: $toId
    maleOnly: $maleOnly
  ) {
    fromPersonId
    toPersonId
    found
    distance
    pathPersonIds
    relationshipTypes
    paths {
      distance
      pathPersonIds
      relationshipTypes
    }
  }
}

query AlternativeRelationshipPaths(
  $treeId: UUID!
  $fromId: UUID!
  $toId: UUID!
  $maleOnly: Boolean = false
) {
  alternativeRelationshipPaths(
    treeId: $treeId
    fromPersonId: $fromId
    toPersonId: $toId
    maleOnly: $maleOnly
  ) {
    fromPersonId
    toPersonId
    found
    distance
    pathPersonIds
    relationshipTypes
    paths {
      distance
      pathPersonIds
      relationshipTypes
    }
  }
}
