query ClosestRelationship($treeId: UUID!, $fromId: UUID!, $toId: UUID!) {
  closestRelationship(treeId: $treeId, fromPersonId: $fromId, toPersonId: $toId) {
    fromPersonId
    toPersonId
    found
    distance
    pathPersonIds
    relationshipTypes
    paths {
      distance
      pathPersonIds
      relationshipTypes
    }
  }
}

query AlternativeRelationshipPaths($treeId: UUID!, $fromId: UUID!, $toId: UUID!) {
  alternativeRelationshipPaths(
    treeId: $treeId
    fromPersonId: $fromId
    toPersonId: $toId
  ) {
    fromPersonId
    toPersonId
    found
    distance
    pathPersonIds
    relationshipTypes
    paths {
      distance
      pathPersonIds
      relationshipTypes
    }
  }
}
