version: "3.9"

services:

  api:
    build: .
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - neo4j

  celery_worker:
    build: .
    command: celery -A app.celery.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - neo4j

  celery_beat:
    build: .
    command: celery -A app.celery.celery_app beat --loglevel=info
    env_file:
      - .env
    volumes:
      - celerybeat_data:/app/celerybeat
    depends_on:
      - db
      - redis
      - neo4j

  flower:
    build: .
    command: celery -A app.celery.celery_app flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - neo4j

  redis:
    image: redis:8

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
      - neo4j_import:/import

volumes:
  postgres_data:
  celerybeat_data:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import:
