from typing import cast

from fastapi import Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from starlette.responses import Response

from app.presentation.rest.errors.error_resolver import resolve_message
from app.presentation.rest.utils.language import detect_language
from app.utils.app_exception import AppException


class ErrorResponse(BaseModel):
    code: str
    message: str
    status: int
    trace_id: str | None = None
    details: str | None = None


async def app_exception_handler(request: Request, exc: Exception) -> Response:
    """
    Global exception handler for handling domain-level AppException errors.

    This handler:
    - Detects user language (fa/en)
    - Converts domain error codes to localized error messages
    - Returns structured JSON error responses
    - Includes trace_id for debugging and tracking across system logs

    Returns:
        Response:
            A JSONResponse containing error details such as:
            - error_code: Enum of the domain error
            - message: Localized user-friendly message
            - status: HTTP status code associated with domain error
            - trace_id: Unique request identifier generated by middleware
            - detail: Developer-level internal detail message (if available)

    Example response:
        {
            "error_code": "UNDERAGE_MARRIAGE",
            "message": "ازدواج برای افراد زیر سن قانونی مجاز نیست",
            "status": 422,
            "trace_id": "c1349b42d1f84a9b",
            "detail": "Domain rule violated"
        }
    """

    # Convert the incoming exception to AppException type
    app_exc = cast(AppException, exc)

    # Detect client language from the Accept-Language header
    lang = detect_language(request)

    # Resolve localized error message (fa/en)
    message = resolve_message(app_exc.code, lang)

    # Retrieve trace_id (set by TraceMiddleware)
    trace_id = getattr(request.state, "trace_id", None)

    # Build the error response
    return JSONResponse(
        status_code=app_exc.status_code,
        content={
            "error_code": app_exc.code,
            "message": message,
            "status": app_exc.status_code,
            "trace_id": trace_id,
            "detail": app_exc.detail,
        },
    )
