"""unique person's name

Revision ID: 10dbf40ac7aa
Revises: 9fafa5c9c46d
Create Date: 2026-05-07 15:53:01.597108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dbf40ac7aa'
down_revision: Union[str, Sequence[str], None] = '9fafa5c9c46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    # ### end Alembic commands ###
