"""initial schema

Revision ID: 1f77f42995da
Revises:
Create Date: 2026-03-28 00:35:53.978679

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f77f42995da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("father_id", sa.Integer(), nullable=True),
        sa.Column("mother_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["father_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "marriages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("husband_id", sa.Integer(), nullable=False),
        sa.Column("wife_id", sa.Integer(), nullable=False),
        sa.Column("married_at", sa.Date(), nullable=False),
        sa.Column("divorced_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["husband_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wife_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("marriages")
    op.drop_table("persons")
    # ### end Alembic commands ###
