"""uniqe persons name with father and mother id

Revision ID: 468ab146bc68
Revises: 5ed287428c2d
Create Date: 2026-05-07 19:00:56.659061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468ab146bc68'
down_revision: Union[str, Sequence[str], None] = '5ed287428c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.create_unique_constraint('uq_person_name_parents', 'persons', ['name', 'father_id', 'mother_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_person_name_parents', 'persons', type_='unique')
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    # ### end Alembic commands ###
