"""message

Revision ID: d9f299c48c6a
Revises: 1f77f42995da
Create Date: 2026-03-31 19:45:58.012065

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9f299c48c6a"
down_revision: str | Sequence[str] | None = "1f77f42995da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "marriages", ["husband_id", "wife_id", "married_at"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "marriages", type_="unique")
    # ### end Alembic commands ###
