"""message

Revision ID: e0c82c8fd577
Revises: d9f299c48c6a
Create Date: 2026-03-31 19:58:14.615693

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e0c82c8fd577"
down_revision: str | Sequence[str] | None = "d9f299c48c6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
