"""message

Revision ID: e836da88aa95
Revises: e0c82c8fd577
Create Date: 2026-03-31 20:59:53.813674

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e836da88aa95"
down_revision: str | Sequence[str] | None = "e0c82c8fd577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("persons_father_id_fkey"), "persons", type_="foreignkey")
    op.drop_constraint(op.f("persons_mother_id_fkey"), "persons", type_="foreignkey")
    op.create_foreign_key(
        None, "persons", "persons", ["mother_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "persons", "persons", ["father_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "persons", type_="foreignkey")
    op.drop_constraint(None, "persons", type_="foreignkey")
    op.create_foreign_key(
        op.f("persons_mother_id_fkey"), "persons", "persons", ["mother_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("persons_father_id_fkey"), "persons", "persons", ["father_id"], ["id"]
    )
    # ### end Alembic commands ###
