"""Hardcoded starter genealogies provisioned for every self-signup.

The records mirror ``Karimi-Family-export-en.xlsx`` and
``family-tree-export-en.xlsx``. Keeping them as typed constants means runtime
registration does not depend on workbook files or openpyxl.
"""

from dataclasses import dataclass
from typing import NamedTuple


class StarterPersonRow(NamedTuple):
    ref: str
    name: str
    family_name: str | None
    gender: str
    birth_date: str | None
    death_date: str | None
    birth_place: str | None
    death_place: str | None
    notes: str | None
    parent1_ref: str | None
    parent1_type: str | None
    parent2_ref: str | None
    parent2_type: str | None
    marriage_ref: str | None


class StarterMarriageRow(NamedTuple):
    ref: str
    spouse_a_ref: str
    spouse_b_ref: str
    married_at: str
    divorced_at: str | None


@dataclass(frozen=True, slots=True)
class StarterTreeTemplate:
    persons: tuple[StarterPersonRow, ...]
    marriages: tuple[StarterMarriageRow, ...]


KARIMI_EN = StarterTreeTemplate(
    persons=(
        StarterPersonRow(
            "P1",
            "Ali",
            "Karimi",
            "male",
            "1994-05-16",
            None,
            "Tehran",
            None,
            "Try paths Ali ↔ Darya and Ali ↔ Kian.",
            "P16",
            "biological",
            "P12",
            "biological",
            "M5",
        ),
        StarterPersonRow(
            "P2",
            "Amir",
            "Kazemi",
            "male",
            "1970-05-16",
            None,
            "Qom",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P3",
            "Darya",
            "Mousavi",
            "female",
            "1996-01-28",
            None,
            "Tehran",
            None,
            None,
            "P18",
            "biological",
            "P5",
            "biological",
            "M6",
        ),
        StarterPersonRow(
            "P4",
            "Ebrahim",
            "Rezaei",
            "male",
            "1920-01-30",
            "1998-07-21",
            "Shiraz",
            "Shiraz",
            "Founder of the Rezaei line.",
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P5",
            "Farhad",
            "Mousavi",
            "male",
            "1968-03-22",
            None,
            "Tabriz",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P6",
            "Fatemeh",
            "Karimi",
            "female",
            "1997-09-09",
            None,
            "Tehran",
            None,
            None,
            "P16",
            "biological",
            "P12",
            "biological",
            "M5",
        ),
        StarterPersonRow(
            "P7",
            "Hassan",
            "Karimi",
            "male",
            "1918-03-12",
            "1995-11-02",
            "Isfahan",
            "Isfahan",
            "Founder of the Karimi line.",
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P8",
            "Kazem",
            "Rezaei",
            "male",
            "1947-04-18",
            None,
            "Shiraz",
            None,
            None,
            "P4",
            "biological",
            "P17",
            "biological",
            "M2",
        ),
        StarterPersonRow(
            "P9",
            "Kian",
            "Rezaei",
            "male",
            "1998-11-03",
            None,
            "Tehran",
            None,
            None,
            "P15",
            "biological",
            "P19",
            "biological",
            "M7",
        ),
        StarterPersonRow(
            "P10",
            "Leila",
            "Rezaei",
            "female",
            "1944-11-05",
            None,
            "Shiraz",
            None,
            None,
            "P4",
            "biological",
            "P17",
            "biological",
            "M2",
        ),
        StarterPersonRow(
            "P11",
            "Mahmoud",
            "Karimi",
            "male",
            "1942-02-20",
            None,
            "Isfahan",
            None,
            None,
            "P7",
            "biological",
            "P20",
            "biological",
            "M1",
        ),
        StarterPersonRow(
            "P12",
            "Maryam",
            "Hosseini",
            "female",
            "1971-12-01",
            None,
            "Mashhad",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P13",
            "Mina",
            "Rezaei",
            "female",
            "1972-09-09",
            None,
            "Tehran",
            None,
            None,
            "P14",
            "biological",
            "P8",
            "biological",
            "M4",
        ),
        StarterPersonRow(
            "P14",
            "Narges",
            "Karimi",
            "female",
            "1945-07-07",
            None,
            "Isfahan",
            None,
            None,
            "P7",
            "biological",
            "P20",
            "biological",
            "M1",
        ),
        StarterPersonRow(
            "P15",
            "Omid",
            "Rezaei",
            "male",
            "1969-02-02",
            None,
            "Tehran",
            None,
            "Double first cousin of Reza — try path search Reza ↔ Omid.",
            "P14",
            "biological",
            "P8",
            "biological",
            "M4",
        ),
        StarterPersonRow(
            "P16",
            "Reza",
            "Karimi",
            "male",
            "1967-06-30",
            None,
            "Tehran",
            None,
            "Double first cousin of Omid — try path search Reza ↔ Omid.",
            "P11",
            "biological",
            "P10",
            "biological",
            "M3",
        ),
        StarterPersonRow(
            "P17",
            "Sakineh",
            "Ahmadi",
            "female",
            "1924-05-08",
            "2004-12-03",
            "Shiraz",
            "Shiraz",
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P18",
            "Sara",
            "Karimi",
            "female",
            "1970-10-12",
            None,
            "Tehran",
            None,
            None,
            "P11",
            "biological",
            "P10",
            "biological",
            "M3",
        ),
        StarterPersonRow(
            "P19",
            "Shiva",
            "Nouri",
            "female",
            "1973-08-14",
            None,
            "Karaj",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P20",
            "Zahra",
            "Mohammadi",
            "female",
            "1922-08-19",
            "2001-04-14",
            "Isfahan",
            "Isfahan",
            None,
            None,
            None,
            None,
            None,
            None,
        ),
    ),
    marriages=(
        StarterMarriageRow("M1", "P7", "P20", "1941-01-01", None),
        StarterMarriageRow("M2", "P4", "P17", "1942-09-10", None),
        StarterMarriageRow("M3", "P11", "P10", "1965-04-22", None),
        StarterMarriageRow("M4", "P8", "P14", "1968-06-18", None),
        StarterMarriageRow("M5", "P16", "P12", "1992-04-11", None),
        StarterMarriageRow("M6", "P5", "P18", "1994-08-20", None),
        StarterMarriageRow("M7", "P15", "P19", "1995-03-05", None),
        StarterMarriageRow("M8", "P2", "P13", "1996-10-12", None),
    ),
)


KARIMI_FA = StarterTreeTemplate(
    persons=(
        StarterPersonRow(
            "P1",
            "ابراهیم",
            "رضایی",
            "male",
            "1920-01-30",
            "1998-07-21",
            "شیراز",
            "شیراز",
            "بنیان‌گذار خاندان رضایی.",
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P2",
            "امید",
            "رضایی",
            "male",
            "1969-02-02",
            None,
            "تهران",
            None,
            "پسرعموی مضاعف رضا — جفت پیشنهادی برای مسیر چندتایی: p-009 ↔ p-011.",
            "P18",
            "biological",
            "P19",
            "biological",
            "M4",
        ),
        StarterPersonRow(
            "P3",
            "امیر",
            "کاظمی",
            "male",
            "1970-05-16",
            None,
            "قم",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P4",
            "حسن",
            "کریمی",
            "male",
            "1918-03-12",
            "1995-11-02",
            "اصفهان",
            "اصفهان",
            "بنیان‌گذار خاندان کریمی.",
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P5",
            "دریا",
            "موسوی",
            "female",
            "1996-01-28",
            None,
            "تهران",
            None,
            None,
            "P8",
            "biological",
            "P13",
            "biological",
            "M6",
        ),
        StarterPersonRow(
            "P6",
            "رضا",
            "کریمی",
            "male",
            "1967-06-30",
            None,
            "تهران",
            None,
            "پسرعموی مضاعف امید — جفت پیشنهادی برای مسیر چندتایی: p-009 ↔ p-011.",
            "P15",
            "biological",
            "P14",
            "biological",
            "M3",
        ),
        StarterPersonRow(
            "P7",
            "زهرا",
            "محمدی",
            "female",
            "1922-08-19",
            "2001-04-14",
            "اصفهان",
            "اصفهان",
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P8",
            "سارا",
            "کریمی",
            "female",
            "1970-10-12",
            None,
            "تهران",
            None,
            None,
            "P15",
            "biological",
            "P14",
            "biological",
            "M3",
        ),
        StarterPersonRow(
            "P9",
            "سکینه",
            "احمدی",
            "female",
            "1924-05-08",
            "2004-12-03",
            "شیراز",
            "شیراز",
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P10",
            "شیوا",
            "نوری",
            "female",
            "1973-08-14",
            None,
            "کرج",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P11",
            "علی",
            "کریمی",
            "male",
            "1994-05-16",
            None,
            "تهران",
            None,
            "نوهٔ نسل سوم — جفت‌های پیشنهادی مسیر: p-017 ↔ p-019 و p-017 ↔ p-020.",
            "P6",
            "biological",
            "P16",
            "biological",
            "M5",
        ),
        StarterPersonRow(
            "P12",
            "فاطمه",
            "کریمی",
            "female",
            "1997-09-09",
            None,
            "تهران",
            None,
            None,
            "P6",
            "biological",
            "P16",
            "biological",
            "M5",
        ),
        StarterPersonRow(
            "P13",
            "فرهاد",
            "موسوی",
            "male",
            "1968-03-22",
            None,
            "تبریز",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P14",
            "لیلا",
            "رضایی",
            "female",
            "1944-11-05",
            None,
            "شیراز",
            None,
            None,
            "P1",
            "biological",
            "P9",
            "biological",
            "M2",
        ),
        StarterPersonRow(
            "P15",
            "محمود",
            "کریمی",
            "male",
            "1942-02-20",
            None,
            "اصفهان",
            None,
            None,
            "P4",
            "biological",
            "P7",
            "biological",
            "M1",
        ),
        StarterPersonRow(
            "P16",
            "مریم",
            "حسینی",
            "female",
            "1971-12-01",
            None,
            "مشهد",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        StarterPersonRow(
            "P17",
            "مینا",
            "رضایی",
            "female",
            "1972-09-09",
            None,
            "تهران",
            None,
            None,
            "P18",
            "biological",
            "P19",
            "biological",
            "M4",
        ),
        StarterPersonRow(
            "P18",
            "نرگس",
            "کریمی",
            "female",
            "1945-07-07",
            None,
            "اصفهان",
            None,
            None,
            "P4",
            "biological",
            "P7",
            "biological",
            "M1",
        ),
        StarterPersonRow(
            "P19",
            "کاظم",
            "رضایی",
            "male",
            "1947-04-18",
            None,
            "شیراز",
            None,
            None,
            "P1",
            "biological",
            "P9",
            "biological",
            "M2",
        ),
        StarterPersonRow(
            "P20",
            "کیان",
            "رضایی",
            "male",
            "1998-11-03",
            None,
            "تهران",
            None,
            None,
            "P2",
            "biological",
            "P10",
            "biological",
            "M7",
        ),
    ),
    marriages=(
        StarterMarriageRow("M1", "P4", "P7", "1940-12-31", None),
        StarterMarriageRow("M2", "P1", "P9", "1942-09-10", None),
        StarterMarriageRow("M3", "P15", "P14", "1965-04-22", None),
        StarterMarriageRow("M4", "P19", "P18", "1968-06-18", None),
        StarterMarriageRow("M5", "P6", "P16", "1992-04-11", None),
        StarterMarriageRow("M6", "P13", "P8", "1994-08-20", None),
        StarterMarriageRow("M7", "P2", "P10", "1995-03-05", None),
        StarterMarriageRow("M8", "P3", "P17", "1996-10-12", None),
    ),
)


STARTER_TREE_TEMPLATES: dict[str, StarterTreeTemplate] = {
    "karimi-en": KARIMI_EN,
    "karimi-fa": KARIMI_FA,
}
